# Generated by Django 2.1.7 on 2019-03-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('department', models.CharField(max_length=10, verbose_name='科室')),
                ('result', models.TextField(max_length=300, verbose_name='诊断结果')),
                ('solution', models.TextField(max_length=500, verbose_name='解决方法')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.IntegerField(verbose_name='手机')),
                ('department', models.CharField(max_length=10, verbose_name='科室')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_results', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='health_project_server.Diagnostic_results')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_project_server.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('phone', models.IntegerField(verbose_name='手机')),
                ('sex', models.CharField(max_length=5, verbose_name='性别')),
                ('height', models.FloatField(max_length=200, verbose_name='身高')),
                ('weight', models.FloatField(max_length=500, verbose_name='体重')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('blood_type', models.CharField(max_length=10, verbose_name='血型')),
            ],
        ),
        migrations.AddField(
            model_name='doctor_to_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='health_project_server.User'),
        ),
        migrations.AddField(
            model_name='diagnostic_results',
            name='doctor',
            field=models.ManyToManyField(to='health_project_server.Doctor'),
        ),
        migrations.AddField(
            model_name='diagnostic_results',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='health_project_server.User'),
        ),
    ]
